/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chantiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Chantier resources.
         * @description Retrieves the collection of Chantier resources.
         */
        get: operations["api_chantiers_get_collection"];
        put?: never;
        /**
         * Creates a Chantier resource.
         * @description Creates a Chantier resource.
         */
        post: operations["api_chantiers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chantiers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Chantier resource.
         * @description Retrieves a Chantier resource.
         */
        get: operations["api_chantiers_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Chantier resource.
         * @description Removes the Chantier resource.
         */
        delete: operations["api_chantiers_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Chantier resource.
         * @description Updates the Chantier resource.
         */
        patch: operations["api_chantiers_id_patch"];
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Client resources.
         * @description Retrieves the collection of Client resources.
         */
        get: operations["api_clients_get_collection"];
        put?: never;
        /**
         * Creates a Client resource.
         * @description Creates a Client resource.
         */
        post: operations["api_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Client resource.
         * @description Retrieves a Client resource.
         */
        get: operations["api_clients_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Client resource.
         * @description Removes the Client resource.
         */
        delete: operations["api_clients_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Client resource.
         * @description Updates the Client resource.
         */
        patch: operations["api_clients_id_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Chantier: {
            id?: string;
            adresseRue?: string;
            adresseCodePostal?: string;
            adresseVille?: string;
            adressePays?: string;
            surfaceM2?: number | null;
            statut?: string;
            creeLe?: string;
            modifieLe?: string;
            clientId?: string | null;
            clientNom?: string | null;
        };
        "Chantier.CreerChantierPayload": {
            adresseRue: string;
            adresseCodePostal: string;
            adresseVille: string;
            adressePays?: string;
            surfaceM2?: number | null;
            /** Format: uuid */
            clientId?: string | null;
            /** Format: uuid */
            uuid?: string | null;
        };
        "Chantier.ModifierChantierPayload.jsonMergePatch": {
            adresseRue?: string | null;
            adresseCodePostal?: string | null;
            adresseVille?: string | null;
            adressePays?: string | null;
            surfaceM2?: number | null;
            /** Format: uuid */
            clientId?: string | null;
        };
        "Chantier.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: string;
            adresseRue?: string;
            adresseCodePostal?: string;
            adresseVille?: string;
            adressePays?: string;
            surfaceM2?: number | null;
            statut?: string;
            creeLe?: string;
            modifieLe?: string;
            clientId?: string | null;
            clientNom?: string | null;
        };
        Client: {
            id?: string;
            nom?: string;
            email?: string | null;
            telephone?: string | null;
            adresseRue?: string;
            adresseCodePostal?: string;
            adresseVille?: string;
            adressePays?: string;
            notes?: string | null;
            creeLe?: string;
            modifieLe?: string;
        };
        "Client.CreerClientPayload": {
            nom: string;
            /** Format: email */
            email?: string | null;
            telephone?: string | null;
            adresseRue: string;
            adresseCodePostal: string;
            adresseVille: string;
            adressePays?: string;
            notes?: string | null;
            /** Format: uuid */
            uuid?: string | null;
        };
        "Client.ModifierClientPayload.jsonMergePatch": {
            nom?: string | null;
            /** Format: email */
            email?: string | null;
            telephone?: string | null;
            adresseRue?: string | null;
            adresseCodePostal?: string | null;
            adresseVille?: string | null;
            adressePays?: string | null;
            notes?: string | null;
        };
        "Client.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: string;
            nom?: string;
            email?: string | null;
            telephone?: string | null;
            adresseRue?: string;
            adresseCodePostal?: string;
            adresseVille?: string;
            adressePays?: string;
            notes?: string | null;
            creeLe?: string;
            modifieLe?: string;
        };
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "@type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string;
                /** Format: iri-reference */
                last?: string;
                /** Format: iri-reference */
                previous?: string;
                /** Format: iri-reference */
                next?: string;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_chantiers_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chantier collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chantier"][];
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Chantier.jsonld"][];
                    };
                };
            };
        };
    };
    api_chantiers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Chantier resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Chantier.CreerChantierPayload"];
                "application/ld+json": components["schemas"]["Chantier.CreerChantierPayload"];
            };
        };
        responses: {
            /** @description Chantier resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chantier"];
                    "application/ld+json": components["schemas"]["Chantier.jsonld"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_chantiers_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chantier identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chantier resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chantier"];
                    "application/ld+json": components["schemas"]["Chantier.jsonld"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_chantiers_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chantier identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chantier resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_chantiers_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chantier identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Chantier resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Chantier.ModifierChantierPayload.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Chantier resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chantier"];
                    "application/ld+json": components["schemas"]["Chantier.jsonld"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_clients_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Client.jsonld"][];
                    };
                };
            };
        };
    };
    api_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Client resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Client.CreerClientPayload"];
                "application/ld+json": components["schemas"]["Client.CreerClientPayload"];
            };
        };
        responses: {
            /** @description Client resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                    "application/ld+json": components["schemas"]["Client.jsonld"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_clients_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                    "application/ld+json": components["schemas"]["Client.jsonld"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_clients_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_clients_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Client resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Client.ModifierClientPayload.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Client resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                    "application/ld+json": components["schemas"]["Client.jsonld"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
}
