framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Messenger\Message\GenerateThumbnailMessage: async
            App\Messenger\Message\DeleteR2ObjectMessage: async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
